### ISSUE TITLE
Create pre/post request handlers

### ISSUE THREAD

**Issue by jasonwalsh** [pennsignals/mantis#5]
Perform pre or post processing on the request/response objects.

The [`BaseHandler`](https://docs.python.org/3/library/urllib.request.html#urllib.request.BaseHandler) class provides pre/post processing methods `BaseHandler.protocol_request` and `BaseHandler.protocol_response`.

Unit testing required: @rightlag

**Comment by rightlag** [comment]
The `DefaultRequestHandler` shall be used if a custom handler is not provided in the OpenAPI specification file (`openapi.json`).

The `DefaultRequestHandler` is an abstract class that defines the default functionality of the `before_request` and `after_response` methods, which by default, do nothing.
