### ISSUE TITLE
Create HTTPS Handler for issuing requests using SSL/TLS

### ISSUE THREAD

**Issue by jasonwalsh** [pennsignals/mantis#6]
The intent of the handler is to initialize an `SSLContext` (using a PEM key written to Vault) *before* issuing requests.

**Comment by rightlag** [comment]
The [`HTTPSHandler`](https://docs.python.org/3/library/urllib.request.html#urllib.request.HTTPSHandler) can be used to initialize an `SSLContext` object from Vault.

See: [https://github.com/pennsignals/signalscore/blob/master/signalscore/handler.py#L11](https://github.com/pennsignals/signalscore/blob/master/signalscore/handler.py#L11)
